name: GitHub CI
on:
  push:
    branches: [ 'main' ]

jobs:
  Release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: NPM Install
        run: npm install --ignore-scripts
      - name: Lint Fix
        run: npm run lint:fix
      - name: Semantic Release (Dry Run)
        run: npm run semantic-release:dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Semantic Release
        run: npm run semantic-release
        env:
          GITHUB_TOKEN:  ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}